### ISSUE TITLE
Need to add i to hased bytes?

### ISSUE THREAD

**Issue by raviqqe** [mediocregopher/seq#4]
This line to hash `[]byte` is not using `i`. Is it OK?
https://github.com/mediocregopher/seq/blob/master/hashset.go#L65

Or, is it should be like the below?
```go
	case []byte:
		return hash(crc32.ChecksumIEEE(vt), i)
```

**Comment by mediocregopher** [comment]
I'll be honest, it's been a long long time since I've looked at this code, and I don't quite remember what that `i` was even for >_< But my comment on the `Hash` method indicates that `i` is a best-effort thing, so it doesn't _need_ to be taken into account, it just should be if possible. Were you encountering problems because of this? Your change looks like it would be fine, if you want to submit another PR.

**Comment by raviqqe** [comment]
My code using your library works pretty well. I just wonder why the code doesn't use `i` and guessed it's a bug. I don't wanna touch the current code because I don't understand what it does exactly. :)
You can just close this issue if you don't care about it.

**Comment by mediocregopher** [comment]
Ok, well if you see any problems that might be a result of this definitely reopen this issue and we can figure it out. Thanks!
